// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vcs

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"github.com/zapier/kubechecks/pkg"
	"github.com/zapier/kubechecks/pkg/msg"
	"github.com/zapier/kubechecks/pkg/vcs"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CloneUsername provides a mock function for the type MockClient
func (_mock *MockClient) CloneUsername() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloneUsername")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_CloneUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneUsername'
type MockClient_CloneUsername_Call struct {
	*mock.Call
}

// CloneUsername is a helper method to define mock.On call
func (_e *MockClient_Expecter) CloneUsername() *MockClient_CloneUsername_Call {
	return &MockClient_CloneUsername_Call{Call: _e.mock.On("CloneUsername")}
}

func (_c *MockClient_CloneUsername_Call) Run(run func()) *MockClient_CloneUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_CloneUsername_Call) Return(s string) *MockClient_CloneUsername_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_CloneUsername_Call) RunAndReturn(run func() string) *MockClient_CloneUsername_Call {
	_c.Call.Return(run)
	return _c
}

// CommitStatus provides a mock function for the type MockClient
func (_mock *MockClient) CommitStatus(context1 context.Context, pullRequest vcs.PullRequest, commitState pkg.CommitState) error {
	ret := _mock.Called(context1, pullRequest, commitState)

	if len(ret) == 0 {
		panic("no return value specified for CommitStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest, pkg.CommitState) error); ok {
		r0 = returnFunc(context1, pullRequest, commitState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CommitStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitStatus'
type MockClient_CommitStatus_Call struct {
	*mock.Call
}

// CommitStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - pullRequest vcs.PullRequest
//   - commitState pkg.CommitState
func (_e *MockClient_Expecter) CommitStatus(context1 interface{}, pullRequest interface{}, commitState interface{}) *MockClient_CommitStatus_Call {
	return &MockClient_CommitStatus_Call{Call: _e.mock.On("CommitStatus", context1, pullRequest, commitState)}
}

func (_c *MockClient_CommitStatus_Call) Run(run func(context1 context.Context, pullRequest vcs.PullRequest, commitState pkg.CommitState)) *MockClient_CommitStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.PullRequest
		if args[1] != nil {
			arg1 = args[1].(vcs.PullRequest)
		}
		var arg2 pkg.CommitState
		if args[2] != nil {
			arg2 = args[2].(pkg.CommitState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CommitStatus_Call) Return(err error) *MockClient_CommitStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CommitStatus_Call) RunAndReturn(run func(context1 context.Context, pullRequest vcs.PullRequest, commitState pkg.CommitState) error) *MockClient_CommitStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHook provides a mock function for the type MockClient
func (_mock *MockClient) CreateHook(ctx context.Context, repoName string, webhookUrl string, webhookSecret string) error {
	ret := _mock.Called(ctx, repoName, webhookUrl, webhookSecret)

	if len(ret) == 0 {
		panic("no return value specified for CreateHook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, repoName, webhookUrl, webhookSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHook'
type MockClient_CreateHook_Call struct {
	*mock.Call
}

// CreateHook is a helper method to define mock.On call
//   - ctx context.Context
//   - repoName string
//   - webhookUrl string
//   - webhookSecret string
func (_e *MockClient_Expecter) CreateHook(ctx interface{}, repoName interface{}, webhookUrl interface{}, webhookSecret interface{}) *MockClient_CreateHook_Call {
	return &MockClient_CreateHook_Call{Call: _e.mock.On("CreateHook", ctx, repoName, webhookUrl, webhookSecret)}
}

func (_c *MockClient_CreateHook_Call) Run(run func(ctx context.Context, repoName string, webhookUrl string, webhookSecret string)) *MockClient_CreateHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateHook_Call) Return(err error) *MockClient_CreateHook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateHook_Call) RunAndReturn(run func(ctx context.Context, repoName string, webhookUrl string, webhookSecret string) error) *MockClient_CreateHook_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadArchive provides a mock function for the type MockClient
func (_mock *MockClient) DownloadArchive(ctx context.Context, pr vcs.PullRequest) (string, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for DownloadArchive")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest) (string, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest) string); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vcs.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DownloadArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadArchive'
type MockClient_DownloadArchive_Call struct {
	*mock.Call
}

// DownloadArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - pr vcs.PullRequest
func (_e *MockClient_Expecter) DownloadArchive(ctx interface{}, pr interface{}) *MockClient_DownloadArchive_Call {
	return &MockClient_DownloadArchive_Call{Call: _e.mock.On("DownloadArchive", ctx, pr)}
}

func (_c *MockClient_DownloadArchive_Call) Run(run func(ctx context.Context, pr vcs.PullRequest)) *MockClient_DownloadArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.PullRequest
		if args[1] != nil {
			arg1 = args[1].(vcs.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DownloadArchive_Call) Return(s string, err error) *MockClient_DownloadArchive_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_DownloadArchive_Call) RunAndReturn(run func(ctx context.Context, pr vcs.PullRequest) (string, error)) *MockClient_DownloadArchive_Call {
	_c.Call.Return(run)
	return _c
}

// Email provides a mock function for the type MockClient
func (_mock *MockClient) Email() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_Email_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Email'
type MockClient_Email_Call struct {
	*mock.Call
}

// Email is a helper method to define mock.On call
func (_e *MockClient_Expecter) Email() *MockClient_Email_Call {
	return &MockClient_Email_Call{Call: _e.mock.On("Email")}
}

func (_c *MockClient_Email_Call) Run(run func()) *MockClient_Email_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Email_Call) Return(s string) *MockClient_Email_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_Email_Call) RunAndReturn(run func() string) *MockClient_Email_Call {
	_c.Call.Return(run)
	return _c
}

// GetHookByUrl provides a mock function for the type MockClient
func (_mock *MockClient) GetHookByUrl(ctx context.Context, repoName string, webhookUrl string) (*vcs.WebHookConfig, error) {
	ret := _mock.Called(ctx, repoName, webhookUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetHookByUrl")
	}

	var r0 *vcs.WebHookConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*vcs.WebHookConfig, error)); ok {
		return returnFunc(ctx, repoName, webhookUrl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *vcs.WebHookConfig); ok {
		r0 = returnFunc(ctx, repoName, webhookUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vcs.WebHookConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, repoName, webhookUrl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetHookByUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHookByUrl'
type MockClient_GetHookByUrl_Call struct {
	*mock.Call
}

// GetHookByUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - repoName string
//   - webhookUrl string
func (_e *MockClient_Expecter) GetHookByUrl(ctx interface{}, repoName interface{}, webhookUrl interface{}) *MockClient_GetHookByUrl_Call {
	return &MockClient_GetHookByUrl_Call{Call: _e.mock.On("GetHookByUrl", ctx, repoName, webhookUrl)}
}

func (_c *MockClient_GetHookByUrl_Call) Run(run func(ctx context.Context, repoName string, webhookUrl string)) *MockClient_GetHookByUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetHookByUrl_Call) Return(webHookConfig *vcs.WebHookConfig, err error) *MockClient_GetHookByUrl_Call {
	_c.Call.Return(webHookConfig, err)
	return _c
}

func (_c *MockClient_GetHookByUrl_Call) RunAndReturn(run func(ctx context.Context, repoName string, webhookUrl string) (*vcs.WebHookConfig, error)) *MockClient_GetHookByUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockClient
func (_mock *MockClient) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockClient_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetName() *MockClient_GetName_Call {
	return &MockClient_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockClient_GetName_Call) Run(run func()) *MockClient_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetName_Call) Return(s string) *MockClient_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_GetName_Call) RunAndReturn(run func() string) *MockClient_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestFiles provides a mock function for the type MockClient
func (_mock *MockClient) GetPullRequestFiles(ctx context.Context, pr vcs.PullRequest) ([]string, error) {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest) ([]string, error)); ok {
		return returnFunc(ctx, pr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest) []string); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vcs.PullRequest) error); ok {
		r1 = returnFunc(ctx, pr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPullRequestFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestFiles'
type MockClient_GetPullRequestFiles_Call struct {
	*mock.Call
}

// GetPullRequestFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - pr vcs.PullRequest
func (_e *MockClient_Expecter) GetPullRequestFiles(ctx interface{}, pr interface{}) *MockClient_GetPullRequestFiles_Call {
	return &MockClient_GetPullRequestFiles_Call{Call: _e.mock.On("GetPullRequestFiles", ctx, pr)}
}

func (_c *MockClient_GetPullRequestFiles_Call) Run(run func(ctx context.Context, pr vcs.PullRequest)) *MockClient_GetPullRequestFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.PullRequest
		if args[1] != nil {
			arg1 = args[1].(vcs.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetPullRequestFiles_Call) Return(strings []string, err error) *MockClient_GetPullRequestFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_GetPullRequestFiles_Call) RunAndReturn(run func(ctx context.Context, pr vcs.PullRequest) ([]string, error)) *MockClient_GetPullRequestFiles_Call {
	_c.Call.Return(run)
	return _c
}

// LoadHook provides a mock function for the type MockClient
func (_mock *MockClient) LoadHook(ctx context.Context, repoAndId string) (vcs.PullRequest, error) {
	ret := _mock.Called(ctx, repoAndId)

	if len(ret) == 0 {
		panic("no return value specified for LoadHook")
	}

	var r0 vcs.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (vcs.PullRequest, error)); ok {
		return returnFunc(ctx, repoAndId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) vcs.PullRequest); ok {
		r0 = returnFunc(ctx, repoAndId)
	} else {
		r0 = ret.Get(0).(vcs.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoAndId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_LoadHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadHook'
type MockClient_LoadHook_Call struct {
	*mock.Call
}

// LoadHook is a helper method to define mock.On call
//   - ctx context.Context
//   - repoAndId string
func (_e *MockClient_Expecter) LoadHook(ctx interface{}, repoAndId interface{}) *MockClient_LoadHook_Call {
	return &MockClient_LoadHook_Call{Call: _e.mock.On("LoadHook", ctx, repoAndId)}
}

func (_c *MockClient_LoadHook_Call) Run(run func(ctx context.Context, repoAndId string)) *MockClient_LoadHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_LoadHook_Call) Return(pullRequest vcs.PullRequest, err error) *MockClient_LoadHook_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockClient_LoadHook_Call) RunAndReturn(run func(ctx context.Context, repoAndId string) (vcs.PullRequest, error)) *MockClient_LoadHook_Call {
	_c.Call.Return(run)
	return _c
}

// ParseHook provides a mock function for the type MockClient
func (_mock *MockClient) ParseHook(context1 context.Context, request *http.Request, bytes []byte) (vcs.PullRequest, error) {
	ret := _mock.Called(context1, request, bytes)

	if len(ret) == 0 {
		panic("no return value specified for ParseHook")
	}

	var r0 vcs.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, []byte) (vcs.PullRequest, error)); ok {
		return returnFunc(context1, request, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, []byte) vcs.PullRequest); ok {
		r0 = returnFunc(context1, request, bytes)
	} else {
		r0 = ret.Get(0).(vcs.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request, []byte) error); ok {
		r1 = returnFunc(context1, request, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ParseHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseHook'
type MockClient_ParseHook_Call struct {
	*mock.Call
}

// ParseHook is a helper method to define mock.On call
//   - context1 context.Context
//   - request *http.Request
//   - bytes []byte
func (_e *MockClient_Expecter) ParseHook(context1 interface{}, request interface{}, bytes interface{}) *MockClient_ParseHook_Call {
	return &MockClient_ParseHook_Call{Call: _e.mock.On("ParseHook", context1, request, bytes)}
}

func (_c *MockClient_ParseHook_Call) Run(run func(context1 context.Context, request *http.Request, bytes []byte)) *MockClient_ParseHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ParseHook_Call) Return(pullRequest vcs.PullRequest, err error) *MockClient_ParseHook_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockClient_ParseHook_Call) RunAndReturn(run func(context1 context.Context, request *http.Request, bytes []byte) (vcs.PullRequest, error)) *MockClient_ParseHook_Call {
	_c.Call.Return(run)
	return _c
}

// PostMessage provides a mock function for the type MockClient
func (_mock *MockClient) PostMessage(context1 context.Context, pullRequest vcs.PullRequest, s string) (*msg.Message, error) {
	ret := _mock.Called(context1, pullRequest, s)

	if len(ret) == 0 {
		panic("no return value specified for PostMessage")
	}

	var r0 *msg.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest, string) (*msg.Message, error)); ok {
		return returnFunc(context1, pullRequest, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest, string) *msg.Message); ok {
		r0 = returnFunc(context1, pullRequest, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*msg.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, vcs.PullRequest, string) error); ok {
		r1 = returnFunc(context1, pullRequest, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_PostMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostMessage'
type MockClient_PostMessage_Call struct {
	*mock.Call
}

// PostMessage is a helper method to define mock.On call
//   - context1 context.Context
//   - pullRequest vcs.PullRequest
//   - s string
func (_e *MockClient_Expecter) PostMessage(context1 interface{}, pullRequest interface{}, s interface{}) *MockClient_PostMessage_Call {
	return &MockClient_PostMessage_Call{Call: _e.mock.On("PostMessage", context1, pullRequest, s)}
}

func (_c *MockClient_PostMessage_Call) Run(run func(context1 context.Context, pullRequest vcs.PullRequest, s string)) *MockClient_PostMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.PullRequest
		if args[1] != nil {
			arg1 = args[1].(vcs.PullRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_PostMessage_Call) Return(message *msg.Message, err error) *MockClient_PostMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockClient_PostMessage_Call) RunAndReturn(run func(context1 context.Context, pullRequest vcs.PullRequest, s string) (*msg.Message, error)) *MockClient_PostMessage_Call {
	_c.Call.Return(run)
	return _c
}

// TidyOutdatedComments provides a mock function for the type MockClient
func (_mock *MockClient) TidyOutdatedComments(context1 context.Context, pullRequest vcs.PullRequest) error {
	ret := _mock.Called(context1, pullRequest)

	if len(ret) == 0 {
		panic("no return value specified for TidyOutdatedComments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.PullRequest) error); ok {
		r0 = returnFunc(context1, pullRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_TidyOutdatedComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TidyOutdatedComments'
type MockClient_TidyOutdatedComments_Call struct {
	*mock.Call
}

// TidyOutdatedComments is a helper method to define mock.On call
//   - context1 context.Context
//   - pullRequest vcs.PullRequest
func (_e *MockClient_Expecter) TidyOutdatedComments(context1 interface{}, pullRequest interface{}) *MockClient_TidyOutdatedComments_Call {
	return &MockClient_TidyOutdatedComments_Call{Call: _e.mock.On("TidyOutdatedComments", context1, pullRequest)}
}

func (_c *MockClient_TidyOutdatedComments_Call) Run(run func(context1 context.Context, pullRequest vcs.PullRequest)) *MockClient_TidyOutdatedComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.PullRequest
		if args[1] != nil {
			arg1 = args[1].(vcs.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_TidyOutdatedComments_Call) Return(err error) *MockClient_TidyOutdatedComments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_TidyOutdatedComments_Call) RunAndReturn(run func(context1 context.Context, pullRequest vcs.PullRequest) error) *MockClient_TidyOutdatedComments_Call {
	_c.Call.Return(run)
	return _c
}

// ToEmoji provides a mock function for the type MockClient
func (_mock *MockClient) ToEmoji(commitState pkg.CommitState) string {
	ret := _mock.Called(commitState)

	if len(ret) == 0 {
		panic("no return value specified for ToEmoji")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(pkg.CommitState) string); ok {
		r0 = returnFunc(commitState)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_ToEmoji_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToEmoji'
type MockClient_ToEmoji_Call struct {
	*mock.Call
}

// ToEmoji is a helper method to define mock.On call
//   - commitState pkg.CommitState
func (_e *MockClient_Expecter) ToEmoji(commitState interface{}) *MockClient_ToEmoji_Call {
	return &MockClient_ToEmoji_Call{Call: _e.mock.On("ToEmoji", commitState)}
}

func (_c *MockClient_ToEmoji_Call) Run(run func(commitState pkg.CommitState)) *MockClient_ToEmoji_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pkg.CommitState
		if args[0] != nil {
			arg0 = args[0].(pkg.CommitState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ToEmoji_Call) Return(s string) *MockClient_ToEmoji_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_ToEmoji_Call) RunAndReturn(run func(commitState pkg.CommitState) string) *MockClient_ToEmoji_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessage provides a mock function for the type MockClient
func (_mock *MockClient) UpdateMessage(context1 context.Context, message *msg.Message, s string) error {
	ret := _mock.Called(context1, message, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *msg.Message, string) error); ok {
		r0 = returnFunc(context1, message, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type MockClient_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - context1 context.Context
//   - message *msg.Message
//   - s string
func (_e *MockClient_Expecter) UpdateMessage(context1 interface{}, message interface{}, s interface{}) *MockClient_UpdateMessage_Call {
	return &MockClient_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", context1, message, s)}
}

func (_c *MockClient_UpdateMessage_Call) Run(run func(context1 context.Context, message *msg.Message, s string)) *MockClient_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *msg.Message
		if args[1] != nil {
			arg1 = args[1].(*msg.Message)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_UpdateMessage_Call) Return(err error) *MockClient_UpdateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateMessage_Call) RunAndReturn(run func(context1 context.Context, message *msg.Message, s string) error) *MockClient_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Username provides a mock function for the type MockClient
func (_mock *MockClient) Username() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Username")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_Username_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Username'
type MockClient_Username_Call struct {
	*mock.Call
}

// Username is a helper method to define mock.On call
func (_e *MockClient_Expecter) Username() *MockClient_Username_Call {
	return &MockClient_Username_Call{Call: _e.mock.On("Username")}
}

func (_c *MockClient_Username_Call) Run(run func()) *MockClient_Username_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Username_Call) Return(s string) *MockClient_Username_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_Username_Call) RunAndReturn(run func() string) *MockClient_Username_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyHook provides a mock function for the type MockClient
func (_mock *MockClient) VerifyHook(request *http.Request, s string) ([]byte, error) {
	ret := _mock.Called(request, s)

	if len(ret) == 0 {
		panic("no return value specified for VerifyHook")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) ([]byte, error)); ok {
		return returnFunc(request, s)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) []byte); ok {
		r0 = returnFunc(request, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = returnFunc(request, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_VerifyHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyHook'
type MockClient_VerifyHook_Call struct {
	*mock.Call
}

// VerifyHook is a helper method to define mock.On call
//   - request *http.Request
//   - s string
func (_e *MockClient_Expecter) VerifyHook(request interface{}, s interface{}) *MockClient_VerifyHook_Call {
	return &MockClient_VerifyHook_Call{Call: _e.mock.On("VerifyHook", request, s)}
}

func (_c *MockClient_VerifyHook_Call) Run(run func(request *http.Request, s string)) *MockClient_VerifyHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_VerifyHook_Call) Return(bytes []byte, err error) *MockClient_VerifyHook_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClient_VerifyHook_Call) RunAndReturn(run func(request *http.Request, s string) ([]byte, error)) *MockClient_VerifyHook_Call {
	_c.Call.Return(run)
	return _c
}
