apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: httpdump
  namespace: kubechecks
spec:
  generators:
    # this is a simple list generator
    - list:
        elements:
          - name: a
            url:  https://kubernetes.default.svc
          - name: b
            url:  https://kubernetes.default.svc
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: "in-cluster-{{ name }}-httpdump"
      namespace: kubechecks
      labels:
        argocd.argoproj.io/application-set-name: "httpdump"
    spec:
      destination:
        namespace: "httpdump-{{ name }}"
        server: '{{ url }}'
      project: default
      source:
        repoURL: REPO_URL
        targetRevision: HEAD
        path: 'apps/httpdump/overlays/{{ name }}/'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      sources: []
