apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-echo-server
  namespace: kubechecks
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: echo-server
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/echo-server/in-cluster
    repoURL: ${REPO_URL}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
