apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-httpbin
  namespace: kubechecks
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/httpbin/overlays/in-cluster/
    repoURL: ${REPO_URL}
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

