
# /////////////////////////////////////////////////////////////////////////////
# Test ArgoCD Applications
# /////////////////////////////////////////////////////////////////////////////

k8s_kind('Applications', api_version="apiextensions.k8s.io/v1")

def install_test_apps(cfg):
    if config.tilt_subcommand != 'down':
        # Load the terraform url we output, default to gitlab if cant find a vcs-type variable
        vcsPath = "./localdev/terraform/{}/project.url".format(cfg.get('vcs-type', 'gitlab'))
        print("Path to url: " + vcsPath)
        projectUrl=str(read_file(vcsPath, "")).strip('\n')
        print("Remote Project URL: " + projectUrl)

        for app in ["echo-server", "httpbin"]:
            print("Creating Test App: " + app)

            # read the application YAML and patch the repoURL
            objects = read_yaml_stream("localdev/test_apps/{}.yaml".format(app))
            for o in objects:
              o['metadata']['namespace'] = "kubechecks"
              o['spec']['source']['repoURL'] = projectUrl
            k8s_yaml(encode_yaml_stream(objects))

            k8s_resource(
                new_name=app,
                objects=['in-cluster-{}:application'.format(app)],
                labels=["test_apps"],
                resource_deps=["argocd-crds","argocd"],
            )
