with-expecter: true
dir: "mocks/{{.PackageName}}/mocks"
packages:
  github.com/zapier/kubechecks/pkg/vcs:
    config:
      all: true
  github.com/zapier/kubechecks/pkg/vcs/github_client:
    # place your package-specific config here
    config:
      all: true
  github.com/zapier/kubechecks/pkg/generator:
    # place your package-specific config here
    config:
      all: true
  github.com/zapier/kubechecks/pkg/affected_apps:
    # place your package-specific config here
    config:
      all: true
