dir: "mocks/{{.SrcPackageName}}/mocks"
filename: "mock_{{.StructName}}.go"
packages:
  github.com/zapier/kubechecks/pkg/affected_apps:
    config:
      all: true
  github.com/zapier/kubechecks/pkg/generator:
    config:
      all: true
  github.com/zapier/kubechecks/pkg/vcs:
    config:
      all: true
  github.com/zapier/kubechecks/pkg/vcs/github_client:
    config:
      all: true
  github.com/zapier/kubechecks/pkg/vcs/gitlab_client:
    config:
      all: true
