site_name: kubechecks
nav:
  - Home: index.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Contributing: contributing.md
theme:
  name: material

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
