// Code generated by mockery v2.37.1. DO NOT EDIT.

package gitlab_client

import (
	gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// MockMergeRequestsServices is an autogenerated mock type for the MergeRequestsServices type
type MockMergeRequestsServices struct {
	mock.Mock
}

type MockMergeRequestsServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMergeRequestsServices) EXPECT() *MockMergeRequestsServices_Expecter {
	return &MockMergeRequestsServices_Expecter{mock: &_m.Mock}
}

// GetMergeRequest provides a mock function with given fields: pid, mergeRequest, opt, options
func (_m *MockMergeRequestsServices) GetMergeRequest(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestsOptions, options ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, mergeRequest, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.MergeRequest
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestsOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)); ok {
		return rf(pid, mergeRequest, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestsOptions, ...gitlab.RequestOptionFunc) *gitlab.MergeRequest); ok {
		r0 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int, *gitlab.GetMergeRequestsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int, *gitlab.GetMergeRequestsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMergeRequestsServices_GetMergeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequest'
type MockMergeRequestsServices_GetMergeRequest_Call struct {
	*mock.Call
}

// GetMergeRequest is a helper method to define mock.On call
//   - pid interface{}
//   - mergeRequest int
//   - opt *gitlab.GetMergeRequestsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockMergeRequestsServices_Expecter) GetMergeRequest(pid interface{}, mergeRequest interface{}, opt interface{}, options ...interface{}) *MockMergeRequestsServices_GetMergeRequest_Call {
	return &MockMergeRequestsServices_GetMergeRequest_Call{Call: _e.mock.On("GetMergeRequest",
		append([]interface{}{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockMergeRequestsServices_GetMergeRequest_Call) Run(run func(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestsOptions, options ...gitlab.RequestOptionFunc)) *MockMergeRequestsServices_GetMergeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(int), args[2].(*gitlab.GetMergeRequestsOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequest_Call) Return(_a0 *gitlab.MergeRequest, _a1 *gitlab.Response, _a2 error) *MockMergeRequestsServices_GetMergeRequest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequest_Call) RunAndReturn(run func(interface{}, int, *gitlab.GetMergeRequestsOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)) *MockMergeRequestsServices_GetMergeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeRequestChanges provides a mock function with given fields: pid, mergeRequest, opt, options
func (_m *MockMergeRequestsServices) GetMergeRequestChanges(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestChangesOptions, options ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, mergeRequest, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.MergeRequest
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestChangesOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)); ok {
		return rf(pid, mergeRequest, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestChangesOptions, ...gitlab.RequestOptionFunc) *gitlab.MergeRequest); ok {
		r0 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int, *gitlab.GetMergeRequestChangesOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int, *gitlab.GetMergeRequestChangesOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMergeRequestsServices_GetMergeRequestChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequestChanges'
type MockMergeRequestsServices_GetMergeRequestChanges_Call struct {
	*mock.Call
}

// GetMergeRequestChanges is a helper method to define mock.On call
//   - pid interface{}
//   - mergeRequest int
//   - opt *gitlab.GetMergeRequestChangesOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockMergeRequestsServices_Expecter) GetMergeRequestChanges(pid interface{}, mergeRequest interface{}, opt interface{}, options ...interface{}) *MockMergeRequestsServices_GetMergeRequestChanges_Call {
	return &MockMergeRequestsServices_GetMergeRequestChanges_Call{Call: _e.mock.On("GetMergeRequestChanges",
		append([]interface{}{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockMergeRequestsServices_GetMergeRequestChanges_Call) Run(run func(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestChangesOptions, options ...gitlab.RequestOptionFunc)) *MockMergeRequestsServices_GetMergeRequestChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(int), args[2].(*gitlab.GetMergeRequestChangesOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequestChanges_Call) Return(_a0 *gitlab.MergeRequest, _a1 *gitlab.Response, _a2 error) *MockMergeRequestsServices_GetMergeRequestChanges_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequestChanges_Call) RunAndReturn(run func(interface{}, int, *gitlab.GetMergeRequestChangesOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)) *MockMergeRequestsServices_GetMergeRequestChanges_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeRequestDiffVersions provides a mock function with given fields: pid, mergeRequest, opt, options
func (_m *MockMergeRequestsServices) GetMergeRequestDiffVersions(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestDiffVersionsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiffVersion, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, mergeRequest, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*gitlab.MergeRequestDiffVersion
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestDiffVersionsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiffVersion, *gitlab.Response, error)); ok {
		return rf(pid, mergeRequest, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.GetMergeRequestDiffVersionsOptions, ...gitlab.RequestOptionFunc) []*gitlab.MergeRequestDiffVersion); ok {
		r0 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.MergeRequestDiffVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int, *gitlab.GetMergeRequestDiffVersionsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int, *gitlab.GetMergeRequestDiffVersionsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMergeRequestsServices_GetMergeRequestDiffVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequestDiffVersions'
type MockMergeRequestsServices_GetMergeRequestDiffVersions_Call struct {
	*mock.Call
}

// GetMergeRequestDiffVersions is a helper method to define mock.On call
//   - pid interface{}
//   - mergeRequest int
//   - opt *gitlab.GetMergeRequestDiffVersionsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockMergeRequestsServices_Expecter) GetMergeRequestDiffVersions(pid interface{}, mergeRequest interface{}, opt interface{}, options ...interface{}) *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call {
	return &MockMergeRequestsServices_GetMergeRequestDiffVersions_Call{Call: _e.mock.On("GetMergeRequestDiffVersions",
		append([]interface{}{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call) Run(run func(pid interface{}, mergeRequest int, opt *gitlab.GetMergeRequestDiffVersionsOptions, options ...gitlab.RequestOptionFunc)) *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(int), args[2].(*gitlab.GetMergeRequestDiffVersionsOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call) Return(_a0 []*gitlab.MergeRequestDiffVersion, _a1 *gitlab.Response, _a2 error) *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call) RunAndReturn(run func(interface{}, int, *gitlab.GetMergeRequestDiffVersionsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiffVersion, *gitlab.Response, error)) *MockMergeRequestsServices_GetMergeRequestDiffVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListMergeRequestDiffs provides a mock function with given fields: pid, mergeRequest, opt, options
func (_m *MockMergeRequestsServices) ListMergeRequestDiffs(pid interface{}, mergeRequest int, opt *gitlab.ListMergeRequestDiffsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiff, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, mergeRequest, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*gitlab.MergeRequestDiff
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.ListMergeRequestDiffsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiff, *gitlab.Response, error)); ok {
		return rf(pid, mergeRequest, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.ListMergeRequestDiffsOptions, ...gitlab.RequestOptionFunc) []*gitlab.MergeRequestDiff); ok {
		r0 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.MergeRequestDiff)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int, *gitlab.ListMergeRequestDiffsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int, *gitlab.ListMergeRequestDiffsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMergeRequestsServices_ListMergeRequestDiffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMergeRequestDiffs'
type MockMergeRequestsServices_ListMergeRequestDiffs_Call struct {
	*mock.Call
}

// ListMergeRequestDiffs is a helper method to define mock.On call
//   - pid interface{}
//   - mergeRequest int
//   - opt *gitlab.ListMergeRequestDiffsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockMergeRequestsServices_Expecter) ListMergeRequestDiffs(pid interface{}, mergeRequest interface{}, opt interface{}, options ...interface{}) *MockMergeRequestsServices_ListMergeRequestDiffs_Call {
	return &MockMergeRequestsServices_ListMergeRequestDiffs_Call{Call: _e.mock.On("ListMergeRequestDiffs",
		append([]interface{}{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockMergeRequestsServices_ListMergeRequestDiffs_Call) Run(run func(pid interface{}, mergeRequest int, opt *gitlab.ListMergeRequestDiffsOptions, options ...gitlab.RequestOptionFunc)) *MockMergeRequestsServices_ListMergeRequestDiffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(int), args[2].(*gitlab.ListMergeRequestDiffsOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockMergeRequestsServices_ListMergeRequestDiffs_Call) Return(_a0 []*gitlab.MergeRequestDiff, _a1 *gitlab.Response, _a2 error) *MockMergeRequestsServices_ListMergeRequestDiffs_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMergeRequestsServices_ListMergeRequestDiffs_Call) RunAndReturn(run func(interface{}, int, *gitlab.ListMergeRequestDiffsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.MergeRequestDiff, *gitlab.Response, error)) *MockMergeRequestsServices_ListMergeRequestDiffs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMergeRequest provides a mock function with given fields: pid, mergeRequest, opt, options
func (_m *MockMergeRequestsServices) UpdateMergeRequest(pid interface{}, mergeRequest int, opt *gitlab.UpdateMergeRequestOptions, options ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, mergeRequest, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.MergeRequest
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.UpdateMergeRequestOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)); ok {
		return rf(pid, mergeRequest, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int, *gitlab.UpdateMergeRequestOptions, ...gitlab.RequestOptionFunc) *gitlab.MergeRequest); ok {
		r0 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int, *gitlab.UpdateMergeRequestOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int, *gitlab.UpdateMergeRequestOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMergeRequestsServices_UpdateMergeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMergeRequest'
type MockMergeRequestsServices_UpdateMergeRequest_Call struct {
	*mock.Call
}

// UpdateMergeRequest is a helper method to define mock.On call
//   - pid interface{}
//   - mergeRequest int
//   - opt *gitlab.UpdateMergeRequestOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockMergeRequestsServices_Expecter) UpdateMergeRequest(pid interface{}, mergeRequest interface{}, opt interface{}, options ...interface{}) *MockMergeRequestsServices_UpdateMergeRequest_Call {
	return &MockMergeRequestsServices_UpdateMergeRequest_Call{Call: _e.mock.On("UpdateMergeRequest",
		append([]interface{}{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockMergeRequestsServices_UpdateMergeRequest_Call) Run(run func(pid interface{}, mergeRequest int, opt *gitlab.UpdateMergeRequestOptions, options ...gitlab.RequestOptionFunc)) *MockMergeRequestsServices_UpdateMergeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(int), args[2].(*gitlab.UpdateMergeRequestOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockMergeRequestsServices_UpdateMergeRequest_Call) Return(_a0 *gitlab.MergeRequest, _a1 *gitlab.Response, _a2 error) *MockMergeRequestsServices_UpdateMergeRequest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMergeRequestsServices_UpdateMergeRequest_Call) RunAndReturn(run func(interface{}, int, *gitlab.UpdateMergeRequestOptions, ...gitlab.RequestOptionFunc) (*gitlab.MergeRequest, *gitlab.Response, error)) *MockMergeRequestsServices_UpdateMergeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMergeRequestsServices creates a new instance of MockMergeRequestsServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMergeRequestsServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMergeRequestsServices {
	mock := &MockMergeRequestsServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
