// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gitlab_client

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/xanzy/go-gitlab"
)

// NewMockPipelinesServices creates a new instance of MockPipelinesServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPipelinesServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPipelinesServices {
	mock := &MockPipelinesServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPipelinesServices is an autogenerated mock type for the PipelinesServices type
type MockPipelinesServices struct {
	mock.Mock
}

type MockPipelinesServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPipelinesServices) EXPECT() *MockPipelinesServices_Expecter {
	return &MockPipelinesServices_Expecter{mock: &_m.Mock}
}

// ListProjectPipelines provides a mock function for the type MockPipelinesServices
func (_mock *MockPipelinesServices) ListProjectPipelines(pid interface{}, opt *gitlab.ListProjectPipelinesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(pid, opt, options)
	} else {
		tmpRet = _mock.Called(pid, opt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListProjectPipelines")
	}

	var r0 []*gitlab.PipelineInfo
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error)); ok {
		return returnFunc(pid, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) []*gitlab.PipelineInfo); ok {
		r0 = returnFunc(pid, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.PipelineInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPipelinesServices_ListProjectPipelines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectPipelines'
type MockPipelinesServices_ListProjectPipelines_Call struct {
	*mock.Call
}

// ListProjectPipelines is a helper method to define mock.On call
//   - pid interface{}
//   - opt *gitlab.ListProjectPipelinesOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockPipelinesServices_Expecter) ListProjectPipelines(pid interface{}, opt interface{}, options ...interface{}) *MockPipelinesServices_ListProjectPipelines_Call {
	return &MockPipelinesServices_ListProjectPipelines_Call{Call: _e.mock.On("ListProjectPipelines",
		append([]interface{}{pid, opt}, options...)...)}
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) Run(run func(pid interface{}, opt *gitlab.ListProjectPipelinesOptions, options ...gitlab.RequestOptionFunc)) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *gitlab.ListProjectPipelinesOptions
		if args[1] != nil {
			arg1 = args[1].(*gitlab.ListProjectPipelinesOptions)
		}
		var arg2 []gitlab.RequestOptionFunc
		var variadicArgs []gitlab.RequestOptionFunc
		if len(args) > 2 {
			variadicArgs = args[2].([]gitlab.RequestOptionFunc)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) Return(pipelineInfos []*gitlab.PipelineInfo, response *gitlab.Response, err error) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Return(pipelineInfos, response, err)
	return _c
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) RunAndReturn(run func(pid interface{}, opt *gitlab.ListProjectPipelinesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error)) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Return(run)
	return _c
}
