// Code generated by mockery v2.37.1. DO NOT EDIT.

package gitlab_client

import (
	gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// MockCommitsServices is an autogenerated mock type for the CommitsServices type
type MockCommitsServices struct {
	mock.Mock
}

type MockCommitsServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitsServices) EXPECT() *MockCommitsServices_Expecter {
	return &MockCommitsServices_Expecter{mock: &_m.Mock}
}

// SetCommitStatus provides a mock function with given fields: pid, sha, opt, options
func (_m *MockCommitsServices) SetCommitStatus(pid interface{}, sha string, opt *gitlab.SetCommitStatusOptions, options ...gitlab.RequestOptionFunc) (*gitlab.CommitStatus, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, sha, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.CommitStatus
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, string, *gitlab.SetCommitStatusOptions, ...gitlab.RequestOptionFunc) (*gitlab.CommitStatus, *gitlab.Response, error)); ok {
		return rf(pid, sha, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, *gitlab.SetCommitStatusOptions, ...gitlab.RequestOptionFunc) *gitlab.CommitStatus); ok {
		r0 = rf(pid, sha, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.CommitStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, *gitlab.SetCommitStatusOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, sha, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, string, *gitlab.SetCommitStatusOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, sha, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCommitsServices_SetCommitStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCommitStatus'
type MockCommitsServices_SetCommitStatus_Call struct {
	*mock.Call
}

// SetCommitStatus is a helper method to define mock.On call
//   - pid interface{}
//   - sha string
//   - opt *gitlab.SetCommitStatusOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockCommitsServices_Expecter) SetCommitStatus(pid interface{}, sha interface{}, opt interface{}, options ...interface{}) *MockCommitsServices_SetCommitStatus_Call {
	return &MockCommitsServices_SetCommitStatus_Call{Call: _e.mock.On("SetCommitStatus",
		append([]interface{}{pid, sha, opt}, options...)...)}
}

func (_c *MockCommitsServices_SetCommitStatus_Call) Run(run func(pid interface{}, sha string, opt *gitlab.SetCommitStatusOptions, options ...gitlab.RequestOptionFunc)) *MockCommitsServices_SetCommitStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(string), args[2].(*gitlab.SetCommitStatusOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockCommitsServices_SetCommitStatus_Call) Return(_a0 *gitlab.CommitStatus, _a1 *gitlab.Response, _a2 error) *MockCommitsServices_SetCommitStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCommitsServices_SetCommitStatus_Call) RunAndReturn(run func(interface{}, string, *gitlab.SetCommitStatusOptions, ...gitlab.RequestOptionFunc) (*gitlab.CommitStatus, *gitlab.Response, error)) *MockCommitsServices_SetCommitStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommitsServices creates a new instance of MockCommitsServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitsServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitsServices {
	mock := &MockCommitsServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
