// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gitlab_client

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/xanzy/go-gitlab"
)

// NewMockRepositoryFilesServices creates a new instance of MockRepositoryFilesServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryFilesServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryFilesServices {
	mock := &MockRepositoryFilesServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryFilesServices is an autogenerated mock type for the RepositoryFilesServices type
type MockRepositoryFilesServices struct {
	mock.Mock
}

type MockRepositoryFilesServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryFilesServices) EXPECT() *MockRepositoryFilesServices_Expecter {
	return &MockRepositoryFilesServices_Expecter{mock: &_m.Mock}
}

// GetRawFile provides a mock function for the type MockRepositoryFilesServices
func (_mock *MockRepositoryFilesServices) GetRawFile(pid interface{}, fileName string, opt *gitlab.GetRawFileOptions, options ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(pid, fileName, opt, options)
	} else {
		tmpRet = _mock.Called(pid, fileName, opt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRawFile")
	}

	var r0 []byte
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error)); ok {
		return returnFunc(pid, fileName, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) []byte); ok {
		r0 = returnFunc(pid, fileName, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, fileName, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, fileName, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoryFilesServices_GetRawFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawFile'
type MockRepositoryFilesServices_GetRawFile_Call struct {
	*mock.Call
}

// GetRawFile is a helper method to define mock.On call
//   - pid interface{}
//   - fileName string
//   - opt *gitlab.GetRawFileOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockRepositoryFilesServices_Expecter) GetRawFile(pid interface{}, fileName interface{}, opt interface{}, options ...interface{}) *MockRepositoryFilesServices_GetRawFile_Call {
	return &MockRepositoryFilesServices_GetRawFile_Call{Call: _e.mock.On("GetRawFile",
		append([]interface{}{pid, fileName, opt}, options...)...)}
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) Run(run func(pid interface{}, fileName string, opt *gitlab.GetRawFileOptions, options ...gitlab.RequestOptionFunc)) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *gitlab.GetRawFileOptions
		if args[2] != nil {
			arg2 = args[2].(*gitlab.GetRawFileOptions)
		}
		var arg3 []gitlab.RequestOptionFunc
		var variadicArgs []gitlab.RequestOptionFunc
		if len(args) > 3 {
			variadicArgs = args[3].([]gitlab.RequestOptionFunc)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) Return(bytes []byte, response *gitlab.Response, err error) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Return(bytes, response, err)
	return _c
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) RunAndReturn(run func(pid interface{}, fileName string, opt *gitlab.GetRawFileOptions, options ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error)) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Return(run)
	return _c
}
