// Code generated by mockery v2.46.3. DO NOT EDIT.

package gitlab_client

import (
	gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryFilesServices is an autogenerated mock type for the RepositoryFilesServices type
type MockRepositoryFilesServices struct {
	mock.Mock
}

type MockRepositoryFilesServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryFilesServices) EXPECT() *MockRepositoryFilesServices_Expecter {
	return &MockRepositoryFilesServices_Expecter{mock: &_m.Mock}
}

// GetRawFile provides a mock function with given fields: pid, fileName, opt, options
func (_m *MockRepositoryFilesServices) GetRawFile(pid interface{}, fileName string, opt *gitlab.GetRawFileOptions, options ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, fileName, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRawFile")
	}

	var r0 []byte
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error)); ok {
		return rf(pid, fileName, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) []byte); ok {
		r0 = rf(pid, fileName, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, fileName, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, fileName, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryFilesServices_GetRawFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawFile'
type MockRepositoryFilesServices_GetRawFile_Call struct {
	*mock.Call
}

// GetRawFile is a helper method to define mock.On call
//   - pid interface{}
//   - fileName string
//   - opt *gitlab.GetRawFileOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockRepositoryFilesServices_Expecter) GetRawFile(pid interface{}, fileName interface{}, opt interface{}, options ...interface{}) *MockRepositoryFilesServices_GetRawFile_Call {
	return &MockRepositoryFilesServices_GetRawFile_Call{Call: _e.mock.On("GetRawFile",
		append([]interface{}{pid, fileName, opt}, options...)...)}
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) Run(run func(pid interface{}, fileName string, opt *gitlab.GetRawFileOptions, options ...gitlab.RequestOptionFunc)) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(string), args[2].(*gitlab.GetRawFileOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) Return(_a0 []byte, _a1 *gitlab.Response, _a2 error) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryFilesServices_GetRawFile_Call) RunAndReturn(run func(interface{}, string, *gitlab.GetRawFileOptions, ...gitlab.RequestOptionFunc) ([]byte, *gitlab.Response, error)) *MockRepositoryFilesServices_GetRawFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryFilesServices creates a new instance of MockRepositoryFilesServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryFilesServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryFilesServices {
	mock := &MockRepositoryFilesServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
