// Code generated by mockery v2.46.3. DO NOT EDIT.

package gitlab_client

import (
	gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// MockPipelinesServices is an autogenerated mock type for the PipelinesServices type
type MockPipelinesServices struct {
	mock.Mock
}

type MockPipelinesServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPipelinesServices) EXPECT() *MockPipelinesServices_Expecter {
	return &MockPipelinesServices_Expecter{mock: &_m.Mock}
}

// ListProjectPipelines provides a mock function with given fields: pid, opt, options
func (_m *MockPipelinesServices) ListProjectPipelines(pid interface{}, opt *gitlab.ListProjectPipelinesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectPipelines")
	}

	var r0 []*gitlab.PipelineInfo
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error)); ok {
		return rf(pid, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) []*gitlab.PipelineInfo); ok {
		r0 = rf(pid, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.PipelineInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPipelinesServices_ListProjectPipelines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectPipelines'
type MockPipelinesServices_ListProjectPipelines_Call struct {
	*mock.Call
}

// ListProjectPipelines is a helper method to define mock.On call
//   - pid interface{}
//   - opt *gitlab.ListProjectPipelinesOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockPipelinesServices_Expecter) ListProjectPipelines(pid interface{}, opt interface{}, options ...interface{}) *MockPipelinesServices_ListProjectPipelines_Call {
	return &MockPipelinesServices_ListProjectPipelines_Call{Call: _e.mock.On("ListProjectPipelines",
		append([]interface{}{pid, opt}, options...)...)}
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) Run(run func(pid interface{}, opt *gitlab.ListProjectPipelinesOptions, options ...gitlab.RequestOptionFunc)) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(*gitlab.ListProjectPipelinesOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) Return(_a0 []*gitlab.PipelineInfo, _a1 *gitlab.Response, _a2 error) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPipelinesServices_ListProjectPipelines_Call) RunAndReturn(run func(interface{}, *gitlab.ListProjectPipelinesOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.PipelineInfo, *gitlab.Response, error)) *MockPipelinesServices_ListProjectPipelines_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPipelinesServices creates a new instance of MockPipelinesServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPipelinesServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPipelinesServices {
	mock := &MockPipelinesServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
