apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubechecks.fullname" . }}
rules:
  - apiGroups: ['*']
    resources: ['applications', 'appprojects', 'services']
    verbs: ['*']
