{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "kubechecks.secretsName" . }}"
  labels:
    {{- include "kubechecks.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.secrets.env }}
  {{ $k| quote }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
