name: Build multiarch image
description: Builds a multiarch image using Docker Buildx and Makefile

inputs:
  image_tag:
    description: The image tag
    required: true
  push:
    description: True to push image after building, false otherwise
    required: false
    default: "false"
  tag_latest:
    description: Tag latest as well as the provided tag
    default: "false"
  token:
    description: Github token
    required: true

outputs:
  image:
    description: The full image name and tag
    value: ghcr.io/${{ github.repository }}:${{ inputs.image_tag }}

runs:
  using: composite

  steps:
    # Setup QEMU for multi-architecture emulation (ARM64 on x86_64 runners)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    # Setup Docker Buildx with BuildKit
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:latest
          network=host

    # Parse .tool-versions file for version numbers
    - name: Parse tool versions
      uses: wistia/parse-tool-versions@v1.0

    # Setup Go with caching
    - name: Set up Go
      uses: actions/setup-go@v6.1.0
      with:
        go-version: ${{ env.GOLANG_TOOL_VERSION }}
        cache: true

    # Login to GitHub Container Registry
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    # Build multi-architecture image with Makefile
    - name: Build multi-arch image
      shell: bash
      env:
        IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        if [[ "${{ inputs.push }}" == "true" ]]; then
          make push-multiarch

          # Tag as latest if requested
          if [[ "${{ inputs.tag_latest }}" != "false" ]]; then
            docker buildx imagetools create \
              ghcr.io/${{ github.repository }}:${{ inputs.image_tag }} \
              --tag ghcr.io/${{ github.repository }}:latest
          fi
        else
          make build-multiarch
        fi
