configMap:
  create: true
  env:
    KUBECHECKS_LOG_LEVEL: debug
    KUBECHECKS_ENABLE_WEBHOOK_CONTROLLER: "false"
    KUBECHECKS_ARGOCD_API_INSECURE: "true"
    KUBECHECKS_ARGOCD_API_PATH_PREFIX : '/argocd'
    KUBECHECKS_ARGOCD_NAMESPACE: 'kubechecks'
    KUBECHECKS_WEBHOOK_URL_PREFIX: 'kubechecks'
    KUBECHECKS_NAMESPACE: 'kubechecks'
    KUBECHECKS_FALLBACK_K8S_VERSION: "1.25.0"
    KUBECHECKS_SHOW_DEBUG_INFO: "true"
    # OTEL
    KUBECHECKS_OTEL_COLLECTOR_PORT: "4317"
    KUBECHECKS_OTEL_ENABLED: "false"
    # Webhook Management
    KUBECHECKS_ENSURE_WEBHOOKS: "true"
    KUBECHECKS_MONITOR_ALL_APPLICATIONS: "true"
    #
    # KUBECHECKS_LABEL_FILTER: "test" # On your PR/MR, prefix this with "kubechecks:"
    # KUBECHECKS_SCHEMAS_LOCATION: https://github.com/zapier/kubecheck-schemas.git
    KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: "delete"
    KUBECHECKS_ENABLE_CONFTEST: "true"


deployment:
  annotations:
    reloader.stakater.com/auto: "true" 
  
  image:
    pullPolicy: Always
    name: "kubechecks"
    tag: ""

secrets:
  create: true
  env:
    KUBECHECKS_ARGOCD_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJrdWJlY2hlY2tzOmFwaUtleSIsIm5iZiI6MTY3ODg1Mjc3NywiaWF0IjoxNjc4ODUyNzc3LCJqdGkiOiJrdWJlY2hlY2tzLXRpbHQifQ.58-noxH2GO_8J3gfSiKJdLdniBx4j8wbCqzzGxcwxGU'


reloader:
  enabled: true
