configMap:
  create: true
  env: {}


deployment:
  annotations:
    reloader.stakater.com/auto: "true" 
  env:
    - name: KUBECHECKS_LOG_LEVEL
      value: debug
    - name: KUBECHECKS_ENABLE_WEBHOOK_CONTROLLER
      value: "false"
    - name: KUBECHECKS_ARGOCD_API_INSECURE
      value: "true"
    - name: KUBECHECKS_ARGOCD_API_PATH_PREFIX 
      value : '/argocd'
    - name: KUBECHECKS_ARGOCD_NAMESPACE
      value: 'kubechecks'
    - name: KUBECHECKS_WEBHOOK_URL_PREFIX
      value: 'kubechecks'
    - name: KUBECHECKS_NAMESPACE
      value: 'kubechecks'
    - name: KUBECHECKS_FALLBACK_K8S_VERSION
      value: "1.25.0"
    - name: KUBECHECKS_SHOW_DEBUG_INFO
      value: "true"
    # OTEL
    - name: KUBECHECKS_OTEL_COLLECTOR_PORT
      value: "4317"
    - name: KUBECHECKS_OTEL_ENABLED
      value: "false"
    # Webhook Management
    - name: KUBECHECKS_ENSURE_WEBHOOKS
      value: "true"
    - name: KUBECHECKS_MONITOR_ALL_APPLICATIONS
      value: "true"
    #
    # KUBECHECKS_LABEL_FILTER: "test" # On your PR/MR, prefix this with "kubechecks:"
    # KUBECHECKS_SCHEMAS_LOCATION: https://github.com/zapier/kubecheck-schemas.git
    - name: KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE
      value: "delete"
    - name: KUBECHECKS_ENABLE_CONFTEST
      value: "true"

  image:
    pullPolicy: Always
    name: "kubechecks"
    tag: ""

secrets:
  create: true
  env:
    KUBECHECKS_ARGOCD_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJrdWJlY2hlY2tzOmFwaUtleSIsIm5iZiI6MTY3ODg1Mjc3NywiaWF0IjoxNjc4ODUyNzc3LCJqdGkiOiJrdWJlY2hlY2tzLXRpbHQifQ.58-noxH2GO_8J3gfSiKJdLdniBx4j8wbCqzzGxcwxGU'


reloader:
  enabled: true
