// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package generator

import (
	"time"

	"github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// GenerateParams provides a mock function for the type MockGenerator
func (_mock *MockGenerator) GenerateParams(appSetGenerator *v1alpha1.ApplicationSetGenerator, applicationSetInfo *v1alpha1.ApplicationSet) ([]map[string]interface{}, error) {
	ret := _mock.Called(appSetGenerator, applicationSetInfo)

	if len(ret) == 0 {
		panic("no return value specified for GenerateParams")
	}

	var r0 []map[string]interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.ApplicationSetGenerator, *v1alpha1.ApplicationSet) ([]map[string]interface{}, error)); ok {
		return returnFunc(appSetGenerator, applicationSetInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.ApplicationSetGenerator, *v1alpha1.ApplicationSet) []map[string]interface{}); ok {
		r0 = returnFunc(appSetGenerator, applicationSetInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*v1alpha1.ApplicationSetGenerator, *v1alpha1.ApplicationSet) error); ok {
		r1 = returnFunc(appSetGenerator, applicationSetInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_GenerateParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateParams'
type MockGenerator_GenerateParams_Call struct {
	*mock.Call
}

// GenerateParams is a helper method to define mock.On call
//   - appSetGenerator *v1alpha1.ApplicationSetGenerator
//   - applicationSetInfo *v1alpha1.ApplicationSet
func (_e *MockGenerator_Expecter) GenerateParams(appSetGenerator interface{}, applicationSetInfo interface{}) *MockGenerator_GenerateParams_Call {
	return &MockGenerator_GenerateParams_Call{Call: _e.mock.On("GenerateParams", appSetGenerator, applicationSetInfo)}
}

func (_c *MockGenerator_GenerateParams_Call) Run(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator, applicationSetInfo *v1alpha1.ApplicationSet)) *MockGenerator_GenerateParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.ApplicationSetGenerator
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.ApplicationSetGenerator)
		}
		var arg1 *v1alpha1.ApplicationSet
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.ApplicationSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerator_GenerateParams_Call) Return(stringToIfaceVals []map[string]interface{}, err error) *MockGenerator_GenerateParams_Call {
	_c.Call.Return(stringToIfaceVals, err)
	return _c
}

func (_c *MockGenerator_GenerateParams_Call) RunAndReturn(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator, applicationSetInfo *v1alpha1.ApplicationSet) ([]map[string]interface{}, error)) *MockGenerator_GenerateParams_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequeueAfter provides a mock function for the type MockGenerator
func (_mock *MockGenerator) GetRequeueAfter(appSetGenerator *v1alpha1.ApplicationSetGenerator) time.Duration {
	ret := _mock.Called(appSetGenerator)

	if len(ret) == 0 {
		panic("no return value specified for GetRequeueAfter")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.ApplicationSetGenerator) time.Duration); ok {
		r0 = returnFunc(appSetGenerator)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockGenerator_GetRequeueAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequeueAfter'
type MockGenerator_GetRequeueAfter_Call struct {
	*mock.Call
}

// GetRequeueAfter is a helper method to define mock.On call
//   - appSetGenerator *v1alpha1.ApplicationSetGenerator
func (_e *MockGenerator_Expecter) GetRequeueAfter(appSetGenerator interface{}) *MockGenerator_GetRequeueAfter_Call {
	return &MockGenerator_GetRequeueAfter_Call{Call: _e.mock.On("GetRequeueAfter", appSetGenerator)}
}

func (_c *MockGenerator_GetRequeueAfter_Call) Run(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator)) *MockGenerator_GetRequeueAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.ApplicationSetGenerator
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.ApplicationSetGenerator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenerator_GetRequeueAfter_Call) Return(duration time.Duration) *MockGenerator_GetRequeueAfter_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockGenerator_GetRequeueAfter_Call) RunAndReturn(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator) time.Duration) *MockGenerator_GetRequeueAfter_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type MockGenerator
func (_mock *MockGenerator) GetTemplate(appSetGenerator *v1alpha1.ApplicationSetGenerator) *v1alpha1.ApplicationSetTemplate {
	ret := _mock.Called(appSetGenerator)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *v1alpha1.ApplicationSetTemplate
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.ApplicationSetGenerator) *v1alpha1.ApplicationSetTemplate); ok {
		r0 = returnFunc(appSetGenerator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ApplicationSetTemplate)
		}
	}
	return r0
}

// MockGenerator_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockGenerator_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - appSetGenerator *v1alpha1.ApplicationSetGenerator
func (_e *MockGenerator_Expecter) GetTemplate(appSetGenerator interface{}) *MockGenerator_GetTemplate_Call {
	return &MockGenerator_GetTemplate_Call{Call: _e.mock.On("GetTemplate", appSetGenerator)}
}

func (_c *MockGenerator_GetTemplate_Call) Run(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator)) *MockGenerator_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.ApplicationSetGenerator
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.ApplicationSetGenerator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenerator_GetTemplate_Call) Return(applicationSetTemplate *v1alpha1.ApplicationSetTemplate) *MockGenerator_GetTemplate_Call {
	_c.Call.Return(applicationSetTemplate)
	return _c
}

func (_c *MockGenerator_GetTemplate_Call) RunAndReturn(run func(appSetGenerator *v1alpha1.ApplicationSetGenerator) *v1alpha1.ApplicationSetTemplate) *MockGenerator_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}
