// Code generated by mockery v2.37.1. DO NOT EDIT.

package generator

import (
	context "context"

	container "github.com/zapier/kubechecks/pkg/container"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
)

// MockAppsGenerator is an autogenerated mock type for the AppsGenerator type
type MockAppsGenerator struct {
	mock.Mock
}

type MockAppsGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppsGenerator) EXPECT() *MockAppsGenerator_Expecter {
	return &MockAppsGenerator_Expecter{mock: &_m.Mock}
}

// GenerateApplicationSetApps provides a mock function with given fields: ctx, appset, ctr
func (_m *MockAppsGenerator) GenerateApplicationSetApps(ctx context.Context, appset v1alpha1.ApplicationSet, ctr *container.Container) ([]v1alpha1.Application, error) {
	ret := _m.Called(ctx, appset, ctr)

	var r0 []v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha1.ApplicationSet, *container.Container) ([]v1alpha1.Application, error)); ok {
		return rf(ctx, appset, ctr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha1.ApplicationSet, *container.Container) []v1alpha1.Application); ok {
		r0 = rf(ctx, appset, ctr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1alpha1.ApplicationSet, *container.Container) error); ok {
		r1 = rf(ctx, appset, ctr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAppsGenerator_GenerateApplicationSetApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateApplicationSetApps'
type MockAppsGenerator_GenerateApplicationSetApps_Call struct {
	*mock.Call
}

// GenerateApplicationSetApps is a helper method to define mock.On call
//   - ctx context.Context
//   - appset v1alpha1.ApplicationSet
//   - ctr *container.Container
func (_e *MockAppsGenerator_Expecter) GenerateApplicationSetApps(ctx interface{}, appset interface{}, ctr interface{}) *MockAppsGenerator_GenerateApplicationSetApps_Call {
	return &MockAppsGenerator_GenerateApplicationSetApps_Call{Call: _e.mock.On("GenerateApplicationSetApps", ctx, appset, ctr)}
}

func (_c *MockAppsGenerator_GenerateApplicationSetApps_Call) Run(run func(ctx context.Context, appset v1alpha1.ApplicationSet, ctr *container.Container)) *MockAppsGenerator_GenerateApplicationSetApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1alpha1.ApplicationSet), args[2].(*container.Container))
	})
	return _c
}

func (_c *MockAppsGenerator_GenerateApplicationSetApps_Call) Return(_a0 []v1alpha1.Application, _a1 error) *MockAppsGenerator_GenerateApplicationSetApps_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAppsGenerator_GenerateApplicationSetApps_Call) RunAndReturn(run func(context.Context, v1alpha1.ApplicationSet, *container.Container) ([]v1alpha1.Application, error)) *MockAppsGenerator_GenerateApplicationSetApps_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAppsGenerator creates a new instance of MockAppsGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppsGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppsGenerator {
	mock := &MockAppsGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
