// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package a2askills

import (
	"context"

	"github.com/a2aproject/a2a-go/v2/a2a"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type MockClient
func (_mock *MockClient) Call(ctx context.Context, skill string, params map[string]any) (string, error) {
	ret := _mock.Called(ctx, skill, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (string, error)); ok {
		return returnFunc(ctx, skill, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) string); ok {
		r0 = returnFunc(ctx, skill, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, skill, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockClient_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - skill string
//   - params map[string]any
func (_e *MockClient_Expecter) Call(ctx interface{}, skill interface{}, params interface{}) *MockClient_Call_Call {
	return &MockClient_Call_Call{Call: _e.mock.On("Call", ctx, skill, params)}
}

func (_c *MockClient_Call_Call) Run(run func(ctx context.Context, skill string, params map[string]any)) *MockClient_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Call_Call) Return(s string, err error) *MockClient_Call_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_Call_Call) RunAndReturn(run func(ctx context.Context, skill string, params map[string]any) (string, error)) *MockClient_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Discover provides a mock function for the type MockClient
func (_mock *MockClient) Discover(ctx context.Context) ([]a2a.AgentSkill, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 []a2a.AgentSkill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]a2a.AgentSkill, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []a2a.AgentSkill); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]a2a.AgentSkill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type MockClient_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Discover(ctx interface{}) *MockClient_Discover_Call {
	return &MockClient_Discover_Call{Call: _e.mock.On("Discover", ctx)}
}

func (_c *MockClient_Discover_Call) Run(run func(ctx context.Context)) *MockClient_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Discover_Call) Return(agentSkills []a2a.AgentSkill, err error) *MockClient_Discover_Call {
	_c.Call.Return(agentSkills, err)
	return _c
}

func (_c *MockClient_Discover_Call) RunAndReturn(run func(ctx context.Context) ([]a2a.AgentSkill, error)) *MockClient_Discover_Call {
	_c.Call.Return(run)
	return _c
}
