apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindingName | default "kubechecks-remote-role-binding" }}
  namespace: {{ .Values.namespace | default "argocd" }}
subjects:
{{- if .Values.eks.iamRoleArn }}
  - kind: User
    name: {{ .Values.eks.iamRoleArn }}
    apiGroup: rbac.authorization.k8s.io
{{- else if .Values.selfManaged.serviceAccountName }}
  - kind: ServiceAccount
    name: {{ .Values.selfManaged.serviceAccountName }}
    namespace: {{ .Values.namespace | default "argocd" }}
{{- else }}
  {{ fail "Either eks.iamRoleArn, or selfManaged.serviceAccountName must be provided" }}
{{- end }}
roleRef:
  kind: Role
  name: {{ .Values.roleName | default "kubechecks-remote-role" }}
  apiGroup: rbac.authorization.k8s.io
